<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Comment {

	private  $_idComment;
	private  $_postsId;
	private  $_author;
	private  $_content;
	private  $_dateCreation;
	private  $_warning;


	/**
	 * @access public
	 * @param array $values 
	 * @return void
	 */

	public function __construct($values) 
	{
		if (!empty($values))
		{
			$this->hydrate($values);
		}
	}


	/**
	 * @access public
	 * @param array $data 
	 * @return void
	 */

	public function hydrate($datas) 
	{
		foreach ($datas as $key => $value) {
			$method = 'set'.ucfirst($key);
			if (is_callable([$this, $method]))
			{
				$this->$method($value);
			}
		}
	}


	/**
	 * @access public
	 * @return int
	 */

	public function idComment() 
	{
		return $this->_idComment;
	}

	/**
	 * @access public
	 * @return int
	 */

	public function postsId() 
	{
		return $this->_postsId;
	}


	/**
	 * @access public
	 * @return string
	 */

	public function author() 
	{
		return $this->_author;
	}


	/**
	 * @access public
	 * @return string
	 */

	public function content() 
	{
		return $this->_content;
	}


	/**
	 * @access public
	 * @return string
	 */

	public function dateCreation() 
	{
		return $this->_dateCreation;
	}


	/**
	 * @access public
	 * @return bool
	 */

	public function warning() 
	{
		return $this->_warning;
	}


	/**
	 * @access public
	 * @param int $idComment 
	 * @return void
	 */

	public function setIdComment($idComment) 
	{
		if (is_numeric($idComment) && $idComment > 0)
		{
			$this->_idComment = $idComment;
		}
	}

	/**
	 * @access public
	 * @param int $idComment 
	 * @return void
	 */

	public function setPostsId($idPost) 
	{
		if (is_numeric($idPost) && $idPost > 0)
		{
			$this->_postsId = $idPost;
		}
	}


	/**
	 * @access public
	 * @param string $author 
	 * @return void
	 */

	public function setAuthor($author) 
	{
		if(is_string($author) && !empty($author))
		{
			$this->_author = $author;
		}
	}


	/**
	 * @access public
	 * @param string $content 
	 * @return void
	 */

	public function setContent($content) 
	{
		if(is_string($content) && !empty($content))
		{
			$this->_content = $content;
		}
	}


	/**
	 * @access public
	 * @param string $dateCreation 
	 * @return void
	 */

	public function setDateCreation($dateCreation) 
	{
		$this->_dateCreation = $dateCreation;
	}


	/**
	 * @access public
	 * @param bool $warning 
	 * @return void
	 */

	public function setWarning($warning) 
	{
		if (is_numeric($warning)){
			$this->_warning = $warning;
		}
	}


}
