<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Image {


	/**
	 * @access public
	 * @param  $image 
	 * @return void
	 */

	public function saveImage($image) {

	}


	/**
	 * @access public
	 * @param string $imageName 
	 * @return void
	 */

	public function getBigImage($imageName) {

	}


	/**
	 * @access public
	 * @param string $imageName 
	 * @return void
	 */

	public function getSmallImage($imageName) {

	}


}
?>