<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Post {

	
	private  $_id;
	private  $_title;
	private  $_content;
	private  $_dateCreation;
	private  $_dateCreationFormat;
	private  $_dateModif;
	private  $_dateModifFormat;
	private  $_image;
	private  $_alt;
	private  $_draft;


	/**
	 * @access public
	 * @param array $values 
	 * @return void
	 */

	public function __construct($values = array()) 
	{
		if (!empty($values))
		{
			$this->hydrate($values);
		}
	}


	/**
	 * @access public
	 * @param array $data 
	 * @return void
	 */

	public function hydrate($datas) 
	{
		foreach ($datas as $key => $value) {
			$method = 'set'.ucfirst($key);
			if (is_callable([$this, $method]))
			{
				$this->$method($value);
			}
		}


	}


	/**
	 * @access public
	 * @return int
	 */

	public function id() 
	{
		return $this->_id;
	}


	/**
	 * @access public
	 * @return string
	 */

	public function title() 
	{
		return $this->_title;
	}


	/**
	 * @access public
	 * @return string
	 */

	public function content() 
	{
		return $this->_content;
	}


	/**
	 * @access public
	 * @return string
	 */

	public function dateCreation() 
	{
		return $this->_dateCreation;
	}

	/**
	 * @access public
	 * @return string
	 */

	public function dateCreationFormat() 
	{
		return $this->_dateCreationFormat;
	}


	/**
	 * @access public
	 * @return string
	 */

	public function dateModif() 
	{
		return $this->_dateModif;
	}

	/**
	 * @access public
	 * @return string
	 */

	public function dateModifFormat() 
	{
		return $this->_dateModifFormat;
	}

	/**
	 * @access public
	 * @return string
	 */

	public function image() 
	{
		return $this->_image;
	}

	/**
	 * @access public
	 * @return string
	 */

	public function alt() 
	{
		return $this->_alt;
	}

	/**
	 * @access public
	 * @return bool
	 */

	public function draft() 
	{
		return $this->_draft;
	}


	/**
	 * @access public
	 * @param int $id 
	 * @return void
	 */

	public function setId($id) 
	{
		if ($id > 0 && is_numeric($id))
		{
			$this->_id = $id;
		}
	}


	/**
	 * @access public
	 * @param string $title 
	 * @return void
	 */

	public function setTitle($title) 
	{
		if(is_string($title) && !empty($title))
		{
			$this->_title = $title;
		}
	}


	/**
	 * @access public
	 * @param string $content 
	 * @return void
	 */

	public function setContent($content) 
	{
		if(is_string($content) && !empty($content))
		{
			$this->_content = $content;
		}
	}


	/**
	 * @access public
	 * @param string $dateCreation 
	 * @return void
	 */

	public function setDateCreation($dateCreation) 
	{
		$this->_dateCreation = $dateCreation;
	}

	/**
	 * @access public
	 * @param string $dateCreationFormat
	 * @return void
	 */

	public function setDateCreationFormat($dateCreationFormat) 
	{
		$this->_dateCreationFormat = $dateCreationFormat;
	}


	/**
	 * @access public
	 * @param string $dateModif 
	 * @return void
	 */

	public function setDateModif($dateModif) 
	{
		$this->_dateModif = $dateModif;
	}

	/**
	 * @access public
	 * @param string $dateModif 
	 * @return void
	 */

	public function setDateModifFormat($dateModifFormat) 
	{
		$this->_dateModifFormat = $dateModifFormat;
	}


	/**
	 * @access public
	 * @param string $image 
	 * @return void
	 */

	public function setImage($image) 
	{
		if(is_string($image) && !empty($image))
		{
			$this->_image = $image;
		}
	}

	/**
	 * @access public
	 * @param string $alt 
	 * @return void
	 */

	public function setAlt($alt) 
	{
		if(is_string($alt) && !empty($alt))
		{
			$this->_alt = $alt;
		}
	}


	/**
	 * @access public
	 * @param bool $draft 
	 * @return void
	 */

	public function setDraft($draft) 
	{
		if(is_bool($draft) && !empty($draft))
		{
			$this->_draft = $draft;
		}
	}


}
